packages:
  - packages/bruno-app
  - packages/bruno-electron
  - packages/bruno-cli
  - packages/bruno-common
  - packages/bruno-converters
  - packages/bruno-docs
  - packages/bruno-schema
  - packages/bruno-schema-types
  - packages/bruno-query
  - packages/bruno-js
  - packages/bruno-lang
  - packages/bruno-tests
  - packages/bruno-toml
  - packages/bruno-graphql-docs
  - packages/bruno-requests
  - packages/bruno-filestore
